services:
  database:
    build: ./Backend/database
    container_name: database
    restart: always
    networks:
      - spring_net

  admin:
    build: ./Backend/admin
    container_name: admin
    ports:
      - "8081:8081"
    restart: always
    networks:
      - spring_net
      - frontend_net
    depends_on:
      - database

  student:
    build: ./Backend/student
    container_name: student
    ports:
      - "8080:8080"
    restart: always
    networks:
      - spring_net
      - frontend_net
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - frontend_net

networks:
  spring_net:
  frontend_net: